CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';
ALTER USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'oem_app'@'%' IDENTIFIED BY '';
ALTER USER 'oem_app'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON oem_app.* TO 'oem_app'@'%';

FLUSH PRIVILEGES;
